### ISSUE TITLE
安装这个需要python环境吗，为什么我一直安装不成功

### ISSUE THREAD

**Issue by zhanggaodong** [Luomusha/node-twain#5]

**Comment by Luomusha** [comment]
因为使用了node-addon-api. 而这个库需要使用node-gyp编译C++代码。
node-gyp编译时候需要用python和微软vitual studio编译环境。

所以编译时候用到了python。贴出报错提示信息。

**Comment by zhanggaodong** [comment]
`npm ERR! code 1
npm ERR! path G:\测试\扫描仪测试\node_modules\node-twain
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.3.1
npm ERR! gyp info using node@18.16.0 | win32 | x64
npm ERR! gyp info find Python using Python version 3.10.11 found at "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\python.exe"
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS msvs_version not set from command line or npm config
npm ERR! gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
npm ERR! gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details
npm ERR! gyp ERR! find VS looking for Visual Studio 2015
npm ERR! gyp ERR! find VS - not found
npm ERR! gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS You need to install the latest version of Visual Studio
npm ERR! gyp ERR! find VS including the "Desktop development with C++" workload.
npm ERR! gyp ERR! find VS For more information consult the documentation at:
npm ERR! gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Could not find any Visual Studio installation to use
npm ERR! gyp ERR! stack     at VisualStudioFinder.fail (F:\nvm\v18.15.0\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:122:47)
npm ERR! gyp ERR! stack     at F:\nvm\v18.15.0\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:75:16
npm ERR! gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (F:\nvm\v18.15.0\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:369:14)
npm ERR! gyp ERR! stack     at F:\nvm\v18.15.0\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:71:14
npm ERR! gyp ERR! stack     at F:\nvm\v18.15.0\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:390:16
npm ERR! gyp ERR! stack     at F:\nvm\v18.15.0\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
npm ERR! gyp ERR! stack     at F:\nvm\v18.15.0\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:427:5)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
npm ERR! gyp ERR! System Windows_NT 10.0.19045
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "F:\\nvm\\v18.15.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd G:\测试\扫描仪测试\node_modules\node-twain
npm ERR! gyp ERR! node -v v18.16.0
npm ERR! gyp ERR! node-gyp -v v9.3.1
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Local\npm-cache\_logs\2023-05-11T03_32_00_497Z-debug-0.log`

**Comment by Luomusha** [comment]
`Could not find any Visual Studio installation to use`
目前看node-gyp没有找到Visual Studio。电脑需要安装这个。

过段时间我看看能不能把编译好的东西放上去。就不需要你们编译了。

**Comment by fat-shen** [comment]
> 因为使用了node-addon-api. 而这个库需要使用node-gyp编译C++代码。 node-gyp编译时候需要用python和微软vitual studio编译环境。
> 
> 所以编译时候用到了python。贴出报错提示信息。

用vitual studio的话 Mac无法编译？

**Comment by Luomusha** [comment]
> > `Could not find any Visual Studio installation to use` 目前看node-gyp没有找到Visual Studio。电脑需要安装这个。
> > 过段时间我看看能不能把编译好的东西放上去。就不需要你们编译了。
> 
> 我看gyp那个配置，mac用的xcode是吗

很遗憾，TWAIN官方提供的twain-server还没有提供Mac端。我没在Mac上跑通过。
