### ISSUE TITLE
我在electron-vue中安装报错  node版本为 14.0.0 32bit

### ISSUE THREAD

**Issue by wwq146213** [Luomusha/node-twain#7]
![image](https://github.com/Luomusha/node-twain/assets/93062479/cad05067-66f1-485f-a0be-6c4572dfb5d8)

**Comment by Luomusha** [comment]
你的电脑是windows，使用nvm切换成64位的nodejs试试？

**Comment by wwq146213** [comment]
> 你的电脑是windows，使用nvm切换成64位的nodejs测试？

因为我还有其他的dll 要调用 有限制 所以只能使用32为的

**Comment by yuanhongyu123** [comment]
我和你一样的错误，32位和64位的node，错误信息一样，我的node是18.19.0

**Comment by wwq146213** [comment]
> 我和你一样的错误，32位和64位的node，错误信息一样，我的node是18.19.0

你换个14版本 应该是node版本太高了

**Comment by yuanhongyu123** [comment]
> > 我和你一样的错误，32位和64位的node，错误信息一样，我的node是18.19.0
> 
> 你换个14版本 应该是node版本太高了

不行啊，我的构建框架electron-vite刚需node18，你后来怎么解决的啊，是node14+64位就可以了？

**Comment by yuanhongyu123** [comment]
> > 我和你一样的错误，32位和64位的node，错误信息一样，我的node是18.19.0
> 
> 你换个14版本 应该是node版本太高了

我看你最先的报错版本就是node14啊，跟我node18报一样的错，应该不是node版本的问题啊

**Comment by wwq146213** [comment]
> > > 我和你一样的错误，32位和64位的node，错误信息一样，我的node是18.19.0
> > 
> > 
> > 你换个14版本 应该是node版本太高了
> 
> 我看你最先的报错版本就是node14啊，跟我node18报一样的错，应该不是node版本的问题啊

我记得我用node 16的好像成功了  但是因为还有ocr 最多支持到14 所以我只能用14

**Comment by yuanhongyu123** [comment]
> > > > 我和你一样的错误，32位和64位的node，错误信息一样，我的node是18.19.0
> > > 
> > > 
> > > 你换个14版本 应该是node版本太高了
> > 
> > 
> > 我看你最先的报错版本就是node14啊，跟我node18报一样的错，应该不是node版本的问题啊
> 
> 我记得我用node 16的好像成功了 但是因为还有ocr 最多支持到14 所以我只能用14

我发现了，不是node版本的问题，而是必须要64位的，64位下node18也可以安装了。
这是不是说明这个库只能64位使用啊。。

**Comment by wwq146213** [comment]
> > > > > 我和你一样的错误，32位和64位的node，错误信息一样，我的node是18.19.0
> > > > 
> > > > 
> > > > 你换个14版本 应该是node版本太高了
> > > 
> > > 
> > > 我看你最先的报错版本就是node14啊，跟我node18报一样的错，应该不是node版本的问题啊
> > 
> > 
> > 我记得我用node 16的好像成功了 但是因为还有ocr 最多支持到14 所以我只能用14
> 
> 我发现了，不是node版本的问题，而是必须要64位的，64位下node18也可以安装了。 这是不是说明这个库只能64位使用啊。。

是的

**Comment by yuanhongyu123** [comment]
App threw an error during load
Error: Could not dynamically require "D:\OpulenDev\windows\flashtest-client\apps\ft-system\build\twain.node". Please configure the dynamicRequireTargets or/and ignoreDynamicRequires option of @rollup/plugin-commonjs appropriately for this require call to work.
    at commonjsRequire (D:\OpulenDev\windows\flashtest-client\apps\ft-system\out\main\index.cjs:45927:8)
    at bindings (D:\OpulenDev\windows\flashtest-client\apps\ft-system\out\main\index.cjs:78376:49)
    at Object.<anonymous> (D:\OpulenDev\windows\flashtest-client\apps\ft-system\out\main\index.cjs:78447:17)
    at Module._compile (node:internal/modules/cjs/loader:1141:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1196:10)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
    at f._load (node:electron/js2c/asar_bundle:2:13377)
    at loadApplicationPackage (D:\OpulenDev\windows\flashtest-client\node_modules\electron\dist\resources\default_app.asar\main.js:121:16)
    at Object.<anonymous> (D:\OpulenDev\windows\flashtest-client\node_modules\electron\dist\resources\default_app.asar\main.js:233:9)
    
  请教下，有没有碰到这个错误啊，要不能否加个微信咨询咨询啊 我的微信64739739，
  这个twain的库好少，没什么人用。。资料都找不到

**Comment by LevyShang** [comment]
@yuanhongyu123 @wwq146213 不知道你们还用不用了，我发下解决代码吧，其实就是类型转换有点问题
`case TWTY_INT8:
    for (TW_UINT16 index = 0; index < pEnum->NumItems; index++) {
        list.Set(index, Napi::Number::New(env, ((pTW_INT8)&pEnum->ItemList)[index]));
    }
    break;
case TWTY_INT16:
    for (TW_UINT16 index = 0; index < pEnum->NumItems; index++) {
        list.Set(index, Napi::Number::New(env, ((pTW_INT16)&pEnum->ItemList)[index]));
    }
    break;
case TWTY_INT32:
    for (TW_UINT16 index = 0; index < pEnum->NumItems; index++) {
        list.Set(index, Napi::Number::New(env, ((pTW_INT32)&pEnum->ItemList)[index]));
    }
    break;
case TWTY_UINT8:
    for (TW_UINT16 index = 0; index < pEnum->NumItems; index++) {
        list.Set(index, Napi::Number::New(env, ((pTW_UINT8)&pEnum->ItemList)[index]));
    }
    break;
case TWTY_UINT16:
    for (TW_UINT16 index = 0; index < pEnum->NumItems; index++) {
        list.Set(index, Napi::Number::New(env, ((pTW_UINT16)&pEnum->ItemList)[index]));
    }
    break;
case TWTY_UINT32:
    for (TW_UINT16 index = 0; index < pEnum->NumItems; index++) {
        list.Set(index, Napi::Number::New(env, ((pTW_UINT32)&pEnum->ItemList)[index]));
    }
    break;
case TWTY_BOOL:
    for (TW_UINT16 index = 0; index < pEnum->NumItems; index++) {
        list.Set(index, Napi::Boolean::New(env, ((pTW_BOOL)&pEnum->ItemList)[index] != 0));
    }
    break;`
